# Generated by Django 5.2.7 on 2025-11-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="additional_information",
            field=models.TextField(
                blank=True,
                help_text="Additional information about the project",
                verbose_name="Additional Information",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Budget",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("kitchen", "Kitchen Renovation"),
                    ("bathroom", "Bathroom Renovation"),
                    ("basement", "Basement Renovation"),
                    ("roofing", "Roofing"),
                    ("electrical", "Electrical"),
                    ("plumbing", "Plumbing"),
                    ("hvac", "HVAC"),
                    ("flooring", "Flooring"),
                    ("windows_doors", "Windows/Doors"),
                    ("exterior", "Exterior"),
                    ("general", "General Renovation"),
                ],
                default="general",
                max_length=50,
                verbose_name="Project Type",
            ),
        ),
    ]
