# Generated by Django 5.2.7 on 2025-11-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_project_additional_information_project_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="location",
            field=models.CharField(max_length=200, verbose_name="Location"),
        ),
    ]
