# Generated by Django 5.2.7 on 2025-11-09 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_all_projects(apps, schema_editor):
    """Delete all existing projects before adding user field"""
    Project = apps.get_model("core", "Project")
    Project.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_project_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_all_projects, migrations.RunPython.noop),
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
