# Generated by Django 5.2.7 on 2025-11-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_project_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Contractor Name"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Address"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postal Code"
                    ),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=100, verbose_name="State"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "price_range",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Price Range"
                    ),
                ),
                (
                    "service_area",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Service Area"
                    ),
                ),
                (
                    "business_size",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Business Size"
                    ),
                ),
                (
                    "years_in_business",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Years in Business"
                    ),
                ),
                ("services", models.TextField(blank=True, verbose_name="Services")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "specializations",
                    models.TextField(blank=True, verbose_name="Specializations"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rating out of 5.0",
                        max_digits=3,
                        null=True,
                        verbose_name="Rating",
                    ),
                ),
                (
                    "reviews_count",
                    models.IntegerField(default=0, verbose_name="Reviews Count"),
                ),
                (
                    "certifications",
                    models.TextField(blank=True, verbose_name="Certifications"),
                ),
                (
                    "kfw_eligible",
                    models.BooleanField(default=False, verbose_name="KfW Eligible"),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="Source"),
                ),
                (
                    "additional_info",
                    models.TextField(blank=True, verbose_name="Additional Info"),
                ),
                (
                    "project_types",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of project types (e.g., 'kitchen,bathroom,plumbing')",
                        max_length=500,
                        verbose_name="Project Types",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contractor",
                "verbose_name_plural": "Contractors",
                "ordering": ["-rating", "name"],
            },
        ),
    ]
