# Generated by Django 5.2.7 on 2025-11-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_contractor"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="project",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Postal Code"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="state",
            field=models.CharField(blank=True, max_length=100, verbose_name="State"),
        ),
    ]
