# Generated by Django 5.2.7 on 2025-11-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_project_location_to_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, null=True, verbose_name="Budget"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="city",
            field=models.CharField(max_length=100, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="project",
            name="postal_code",
            field=models.CharField(max_length=20, verbose_name="Postal Code"),
        ),
        migrations.AlterField(
            model_name="project",
            name="state",
            field=models.CharField(max_length=100, verbose_name="State"),
        ),
    ]
