# Generated by Django 5.2.7 on 2025-11-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_project_budget_alter_project_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="additional_information",
            field=models.TextField(
                blank=True,
                help_text="Additional information about the project",
                null=True,
                verbose_name="Additional Information",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Budget"
            ),
        ),
    ]
